### ISSUE TITLE
Additional normalization?

### ISSUE THREAD

**Issue by yksaito** [MattPM/dsb#4]
Hi, thank you for providing a great package!!
I am using dsb and Seurat v3 package.

Seurat recommends centered log-ratio (CLR) normalization for CITE-seq data.
(https://satijalab.org/seurat/v3.1/multimodal_vignette.html)
`cbmc <- NormalizeData(cbmc, assay = "ADT", normalization.method = "CLR")`
`cbmc <- ScaleData(cbmc, assay = "ADT")`

For dsb-normalized CITE-seq data, do we need to perform further normalization using Seurat? Or is it not recommended?

**Comment by MattPM** [comment]
Hi, after you use the DSB function, the protein counts are now normalized, you do not need to use the CLR normalization.

If you haven't already, you can check out the workflow for using DSB with Seurat V3 here:
https://mattpm.github.io/dsb/articles/dsb_normalizing_CITEseq_data.html

We discuss pros and cons of normalizing with CLR vs dsb in the preprint: 
https://www.biorxiv.org/content/10.1101/2020.02.24.963603v1

This is how you add the DSB normalized values to the "data" slot of the protein assay:
`# add normalized data back to the object (the singlets defined above as "object")
SNG_SeuratObject = SetAssayData(object = SNG_SeuratObject, assay = "ADT", new.data = normalized_matrix)`

I should also mention that you don't need to scale the protein data (which converts the normalized values for each cell into a z-score relative to all other cells). The magnitude of the DSB value will be lost if you scale and the interpretation is less clear. Dsb values are in the range of -5 to ~30 usually. If you use these DSB values, I recommend analyzing the data without scaling, at least at first (so you don't need to use this command):

`# dont use: 
cbmc <- ScaleData(cbmc, assay = "ADT")`

One thing to keep in mind is if you scale values then subset the data, the values are now relative to cells that are no longer part of the data (so you should usually re-scale the data after subsetting- thats true for RNA too). 

hope that helps!

**Comment by yksaito** [comment]
OK. I see. Thank you so much for great suggestions!!
I will definitely check your preprint :)

**Comment by fredust** [comment]
> Hi, after you use the DSB function, the protein counts are now normalized, you do not need to use the CLR normalization.
> 
> If you haven't already, you can check out the workflow for using DSB with Seurat V3 here: https://mattpm.github.io/dsb/articles/dsb_normalizing_CITEseq_data.html
> 
> We discuss pros and cons of normalizing with CLR vs dsb in the preprint: https://www.biorxiv.org/content/10.1101/2020.02.24.963603v1
> 
> This is how you add the DSB normalized values to the "data" slot of the protein assay: `# add normalized data back to the object (the singlets defined above as "object") SNG_SeuratObject = SetAssayData(object = SNG_SeuratObject, assay = "ADT", new.data = normalized_matrix)`
> 
> I should also mention that you don't need to scale the protein data (which converts the normalized values for each cell into a z-score relative to all other cells). The magnitude of the DSB value will be lost if you scale and the interpretation is less clear. Dsb values are in the range of -5 to ~30 usually. If you use these DSB values, I recommend analyzing the data without scaling, at least at first (so you don't need to use this command):
> 
> `# dont use: cbmc <- ScaleData(cbmc, assay = "ADT")`
> 
> One thing to keep in mind is if you scale values then subset the data, the values are now relative to cells that are no longer part of the data (so you should usually re-scale the data after subsetting- thats true for RNA too).
> 
> hope that helps!

Hello, thank you for designing the great package. 
I noticed that in the end-to-end vignettes, you also included the` ScaleData` in the Seurat WNN workflow using dsb normalized data. Is that mean now you still recommend scaling the data before downstream analysis?
There is another question. If I perform subset analysis for the dataset (for example, exploring the T cell subset), I don't need to normalise the Cite-seq data again, is that correct? Only re-scaled the data is needed for the subset analysis?

Thank you very much.
