### ISSUE TITLE
Error in quantile.default(x, seq(from = 0, to = 1, length = n)) :

### ISSUE THREAD

**Issue by naity** [MattPM/dsb#6]
The following error was encountered while running DSBNormalizeProtein:

```
Error in quantile.default(x, seq(from = 0, to = 1, length = n)) :
missing values and NaN's not allowed if 'na.rm' is FALSE
```

Thank you!

**Comment by MattPM** [comment]
Hi, @naity, it is tough to know where the error might be coming from without a reprex,  knowing what you have already tried to troubleshoot the issue and the function call that produced the error. Do you have a `traceback() ` or a `sessionInfo()` call? Are there NA's in the matrix you're using? Maybe remove those first, but without more info not sure exactly where to start. Happy to help though.

**Comment by MattPM** [comment]
update: @naity this error occurs during denoising, when you have antibodies in the cells (not the empty drops) that have close to zero counts across all cells. I am assuming you used ` denoise.counts = TRUE` Please try checking the distributions of your staining antibodies - run min mean, max on each protein in the stained cells If you have a protein with no counts try removing it and renormalizing(recommended) or set ` denoise.counts = FALSE`

**Comment by naity** [comment]
Thank you for the explanation!
